import Head from "next/head";
import { MDFileReader } from "@/utils";
// import Image from "next/image";

type Props = {
  posts: any;
};

export default function Home({ posts }: Props) {
  console.log("posts", posts);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await MDFileReader();

  return { props: { posts } };
}

export async function getStaticPaths() {
  const posts = await MDFileReader();

  console.log("posts", posts);

  return {
    paths: [],
    fallback: "blocking",
  };
}
